### ISSUE TITLE
Build a mobility BPP application using Strapi

### ISSUE THREAD

**Issue by faizmagic** [beckn/strapi-plugins#123]
### Description:
The current Mobility BPP application, which was using the HumBhiOnline (HBO) BPP, needs to be rebuilt using Strapi. The project will involve considering the Schema data model and making necessary changes accordingly. All updates and changes should be implemented first in the development environment, then in the staging environment, and finally moved to production. 

**Links for Reference:**
- [Strapi Documentation](https://strapi.io/documentation)
- [Schema Data Model Doc](https://docs.google.com/document/d/xyz12345/edit)

**Reference Apps:**
- HumBhiOnline BPP
- Other BPP Implementations

### Goals:
- [x] Rebuild the Mobility BPP application using Strapi.
- [x] Implement Schema data model changes as required.

### Expected Outcome:
- [x] The Mobility BPP application is successfully rebuilt using Strapi.
- [x] All necessary changes to the Schema data model are implemented.
- [x] The application passes through development, staging, and production environments successfully.

### Acceptance Criteria:
- [x] The Mobility BPP application is fully functional and meets the required specifications.
- [x] Schema data model changes are correctly implemented.
- [x] All updates are first made in the development environment, then in staging, and finally moved to production.
- [x] The application is reviewed and approved by stakeholders.

### Mockups / Wireframes:
- [Figma Design](https://www.figma.com/design/FNpABwpFbhfrZgGfcOmHok/Beckn-Mobility-BAP?node-id=679-6771)

### Product Name:
Beckn, Mobility BPP

### Domain:
Mobility

### Tech Skills Needed:
Strapi, Schema Data Modeling, JavaScript

### Complexity:
High

### Category:
Development

### Sub Category:
Rebuild

**Comment by emmayank** [comment]
All functionality completed and reviewed. closing this ticket now
