### ISSUE TITLE
E2E test for ODR

### ISSUE THREAD

**Issue by vishi24** [beckn/strapi-plugins#26]
## Description

The current implementation of the BPP adaptor supports the ODR domain for all endpoints. Additionally, the new plugin requires thorough testing for ODR compatibility. Testing will encompass scrutiny using the postman collection hosted on the sandbox ([link](https://github.com/beckn/beckn-sandbox/tree/main/artefacts/ODR)) and validation from the UI, which currently interfaces with the Strapi BPP adaptor.

## Goals

- [ ] Test the new Strapi plugin with the ODR postman collection.
- [ ] Validate the new Strapi plugin with the existing ODR UI.

## Expected Outcome

The ODR use case undergoes comprehensive testing with the new Strapi plugin, utilizing the postman collection in the sandbox environment and the ODR UI.

## Acceptance Criteria

- [ ] Ensure consistent responses between the Strapi adapter and the Strapi plugin.
- [ ] Ensure seamless functionality of the UI.

## Implementation Details

N/A

## Mockups / Wireframes

N/A

---

[Please note that the following section of the ticket ***must adhere to the specified format as it is crucial for proper project listing.*** Please select only the options mentioned under the headings where applicable.]

### Product Name

Strapi plugin

### Project Name

Strapi plugin

### Tech Skills Needed:

- Node.js
- Strapi
- Postman

### Complexity

Medium

### Category

Test

### Sub Category

Testing

**Comment by em-abee** [comment]
Findings: https://docs.google.com/spreadsheets/d/1ll9mcvqfUG8jKBxYK60eEmKuIZSz9mE0LRwT0Y2N9U4/edit#gid=1185456464
PR: https://github.com/beckn/strapi-plugins/pull/42
