### ISSUE TITLE
Eventhub plugin

### ISSUE THREAD

**Issue by em-abee** [beckn/strapi-plugins#3]
## Description

Create a strapi plugin for calling external API from Strapi based on the order confirmed in the system.The confirm event should be pushed to eventhub provided by Strapi.

## Goals

- [ ] Create plugin with confirm end point
- [ ] Push the confirm event to eventhub
- [ ] Call the machine/external API
- [ ] Plugin will call the on_confirm of BAP after response from external API

## Expected Outcome

Integration with the external API  by consuming eventhub messages.

## Acceptance Criteria

- [ ] Confirm call should push message to eventhub
- [ ] Plugin should call external API
- [ ] on_confirm call should be made from the plugin

## Implementation Details

Use eventhub to emit event to eventhub on confirm call. Create plugin to subscribe to the event and make on_confirm call

### Product Name

Beckn, BPP Strapi

### Complexity

Medium

### Category

Feature

### Sub Category

API

**Comment by faizmagic** [comment]
@vishi24 @vbabuEM, @zoyaashik Given that in init / confirm call, the interaction with external API through plugin happens selectively base don domain or incoming request, how are we factored this in the plugin design. is there an option in the pluigin to configure this. can we ensure that any external dependency like domain or any other flag or criteria  through which the call to plugin is happening is externalised and is factored in the plugin design.

**Comment by vbabuEM** [comment]
I feel if we separate the two parts, it makes it more easier to decide.
1. Streaming to eventhub on requests. - Here we can either stream events for all domains or limit it to industry4.0
2. Subscribing the events by machine-specific plugin. - Ideally here if we subscribe based on bpp_id, it will be most efficient. Less efficient option is to listen to all industry 4.0 events and then filtering in handler based on bpp_id. 
Combining the above with what is possible in the framework, I think we can come with a solution.
