### ISSUE TITLE
E2E test for DHP

### ISSUE THREAD

**Issue by vishi24** [beckn/strapi-plugins#31]
## Description

The current implementation of the BPP adaptor supports the DHP domain for all endpoints. The new plugin requires thorough testing for DHP compatibility. Testing will encompass scrutiny using the postman collection hosted on the sandbox ([link](https://github.com/beckn/beckn-sandbox/tree/main/artefacts/DHP)) 

## Goals

- [ ] Test the new Strapi plugin with the DHP postman collection.

## Expected Outcome

The DHP use case undergoes comprehensive testing with the new Strapi plugin, utilizing the postman collection in the sandbox environment.

## Acceptance Criteria

- [ ] Ensure consistent responses between the Strapi adapter and the Strapi plugin.

## Implementation Details

N/A

## Mockups / Wireframes

N/A

---

[Please note that the following section of the ticket ***must adhere to the specified format as it is crucial for proper project listing.*** Please select only the options mentioned under the headings where applicable.]

### Product Name

Strapi plugin

### Project Name

Strapi plugin

### Tech Skills Needed:

- Node.js
- Strapi
- Postman

### Complexity

Medium

### Category

Test

### Sub Category

Testing

**Comment by em-abee** [comment]
Findings: https://docs.google.com/spreadsheets/d/1ll9mcvqfUG8jKBxYK60eEmKuIZSz9mE0LRwT0Y2N9U4/edit#gid=1185456464
PR: https://github.com/beckn/strapi-plugins/pull/46
