### ISSUE TITLE
E2E test for DSEP

### ISSUE THREAD

**Issue by vishi24** [beckn/strapi-plugins#32]
## Description

The current implementation of the BPP adaptor supports the DSEP domain for all endpoints. The new plugin requires thorough testing for DSEP compatibility. Testing will encompass scrutiny using the postman collection hosted on the sandbox ([link](https://github.com/beckn/beckn-sandbox/tree/main/artefacts/DSEP)) and validation from the UI, which currently interfaces with the Strapi BPP adaptor.This swill include both scholarship and mentoring.

## Goals

- [ ] Test the new Strapi plugin with the DSEP postman collection.
- [ ] Validate the new Strapi plugin with the existing DSEP UI.

## Expected Outcome

The DSEP use case undergoes comprehensive testing with the new Strapi plugin, utilizing the postman collection in the sandbox environment.

## Acceptance Criteria

- [ ] Ensure consistent responses between the Strapi adapter and the Strapi plugin.
- [ ] Ensure seamless functionality of the UI.

## Implementation Details

N/A

## Mockups / Wireframes

N/A

---

[Please note that the following section of the ticket ***must adhere to the specified format as it is crucial for proper project listing.*** Please select only the options mentioned under the headings where applicable.]

### Product Name

Strapi plugin

### Project Name

Strapi plugin

### Tech Skills Needed:

- Node.js
- Strapi
- Postman

### Complexity

Medium

### Category

Test

### Sub Category

Testing

**Comment by shreyvishal** [comment]
Have tested E2E and fixed the shortfalls for integration or Strapi with DSEP domain for Jobs, Scholarships, Mentoring. Training is done by @zoyaashik 

Link for Test Outcomes: [Strapi Plugin Test API](https://docs.google.com/spreadsheets/d/1ll9mcvqfUG8jKBxYK60eEmKuIZSz9mE0LRwT0Y2N9U4/)

PRs for Fixes: 

- [PR for Scholarships and Mentorign](https://github.com/beckn/strapi-plugins/pull/48)
- [PR for JOBS](https://github.com/beckn/strapi-plugins/pull/43)

cc: @vishi24
