### ISSUE TITLE
E2E test for retail domain

### ISSUE THREAD

**Issue by vishi24** [beckn/strapi-plugins#33]
## Description

The current implementation of the BPP adaptor supports the retail domain for all endpoints. The new plugin requires thorough testing for retail compatibility. Testing will encompass scrutiny using the postman collection hosted on the sandbox ([link](https://github.com/beckn/beckn-sandbox/tree/main/artefacts/Retail)) and validation from the UI, which currently interfaces with the Strapi BPP adaptor.

## Goals

- [ ] Test the new Strapi plugin with the retail postman collection.
- [ ] Validate the new Strapi plugin with the existing retail UI.

## Expected Outcome

The retail use case undergoes comprehensive testing with the new Strapi plugin, utilizing the Postman collection in the sandbox environment.

## Acceptance Criteria

- [ ] Ensure consistent responses between the Strapi adapter and the Strapi plugin.
- [ ] Ensure seamless functionality of the UI.

## Implementation Details

N/A

## Mockups / Wireframes

N/A

---

[Please note that the following section of the ticket ***must adhere to the specified format as it is crucial for proper project listing.*** Please select only the options mentioned under the headings where applicable.]

### Product Name

Strapi plugin

### Project Name

Strapi plugin

### Tech Skills Needed:

- Node.js
- Strapi
- Postman

### Complexity

Medium

### Category

Test

### Sub Category

Testing

**Comment by zoyaashik** [comment]
Completed testing and updated findings in the below  sheet

https://docs.google.com/spreadsheets/d/1ll9mcvqfUG8jKBxYK60eEmKuIZSz9mE0LRwT0Y2N9U4/edit#gid=1789099837
