### ISSUE TITLE
Document the Strapi data model and catalogs for domain

### ISSUE THREAD

**Issue by vishi24** [beckn/strapi-plugins#34]
## Description

The Strapi will be used as a single BPP for all the domains, hence, it needs proper testing for each domain. List down all the domains that are currently supported by BECKN from [here](https://github.com/beckn/beckn-sandbox/tree/main/artefacts). Create the information in the below format

| S No. | Domain          | Data Model | Catalog | Missing Data Model | Missing Catalog | Remark       |
|-------|-----------------|------------|---------|--------------------|-----------------|--------------|
| 1     | Domain Name 1   | Yes        | Yes     |  fullfillment            | fullfillment  |              |
| 2     | Domain Name 2   | No        | No      |      No           | No             |    No          |

## Goals

- [ ] Complete listing of missing Strapi data model and catalog domain-wise.

## Expected Outcome

Document which clearly lists all the domains , respective data model status, catalog status and remarks if any.

## Acceptance Criteria

- [ ] Document tat clearly provide the details about data model and catalog status domain-wise.

## Implementation Details

Create an Excel and put the information on confluence under [Beckn building blocks](https://fide-official.atlassian.net/wiki/spaces/BBB/pages/118325249/Catalog+building+block)

## Mockups / Wireframes

NA

---

[Please note that the below section of the ticket ****has to be in the format as mentioned as it is key to enabling proper listing of the project.**** Please only choose the options mentioned under the headings wherever applicable.]

### Product Name

Strapi plugin

### Project Name

Strapi plugin - BPP adapter

### Tech Skills Needed:

NA

### Complexity

Low

### Category

Analysis

### Sub Category

Documentation

**Comment by zoyaashik** [comment]
https://docs.google.com/spreadsheets/d/1zWvyp3L06vU436yTPmyE3D5R5wDImw3DQp8K6LSIzOc/edit?usp=sharing 

Added the link that contains details for missing data model and catalogues that needs to be fulfilled to accommodate Strapi
