### ISSUE TITLE
Rearchitect the Strapi BPP Beckn adapter

### ISSUE THREAD

**Issue by vishi24** [beckn/strapi-plugins#5]
## Description

As per the finalised architecture , the application structure needs to be architected so that the APIs can be rearchitected based on that and it will serve as the base for all the APIs. 

## Goals

- [ ] Rearchitect the application based on the approach.

## Expected Outcome

The basic structure of the application architecture is created based on the approach finalized document.

## Acceptance Criteria

- [ ] New architecture should be completely according to the architecture document without any deviation.

## Implementation Details

NA

## Mockups / Wireframes

NA

### Product Name

Beckn

### Project Name

strapi-plugin

### Organization Name:

FIDE

### Domain

NA

### Tech Skills Needed:

Strapi
Node

### Complexity

Medium

### Category

Enhancement

### Sub Category

Refactoring

**Comment by faizmagic** [comment]
@vishi24 , this is an epic ticket and does not involve development, please add all the subtasks which has been created as goals in this ticket

**Comment by vishi24** [comment]
Since, we are using milestones now, this ticket is not needed.

**Comment by em-abee** [comment]
PR - https://github.com/beckn/strapi-plugins/pull/16
