### ISSUE TITLE
Location based search (String values) in Strapi plugin

### ISSUE THREAD

**Issue by vishi24** [beckn/strapi-plugins#53]
## Description

The current search functionality within the Strapi plugin lacks support for location-based searches. To address this deficiency, it's imperative to incorporate location-based search capabilities into the strapi-plugin. The schema required for enabling location-based search can be found [here](https://app.swaggerhub.com/apis/beckn/beckn-protocol-core-specification/1.1.0#/Location).

There are two types of searches that need to be considered:

1. **String-Based Search**: This type of search is based on string values and can include any of the following criteria:
   - City
   - District
   - State
   - Country
   - Area Code
   
2. **GPS-Based Search**: This involves using GPS coordinates to define a search area, typically represented by a circle. However, for this particular issue, we will focus solely on implementing search functionality based on string values.

This issue is specifically to target String-Based Search. 

 

## Goals

- [ ] Strapi plugin should be able to make location-based searches for location string values.

## Expected Outcome

Items can be searched based on the location of item/provider.

## Acceptance Criteria

- [ ] Working location-based search on Strapi plugin.

## Implementation Details

NA

## Mockups / Wireframes

NA

---

[Please note that the below section of the ticket ****has to be in the format as mentioned as it is key to enabling proper listing of the project.**** Please only choose the options mentioned under the headings wherever applicable.]

### Product Name

Strapi-plugins

### Project Name

strapi plugins

### Tech Skills Needed:

Strapi

### Complexity

Medium

### Category

Development

### Sub Category

Development

**Comment by faizmagic** [comment]
Almost completed the search functionality, searching by the city and gps. the app should respond with all the list of charging stations with in 5 km radius

**Comment by em-abee** [comment]
Tested with location and not sending other search criteria and it's working.
For demo no check for location is happening and BPP is returning all the providers and item present

**Comment by em-abee** [comment]
![Uploading Screenshot 2024-03-18 at 1.04.09 PM.png…]()
