### ISSUE TITLE
Search API

### ISSUE THREAD

**Issue by vishi24** [beckn/strapi-plugins#6]
## Description

Modify the search API based on the new approach that can handle new domains with configuration changes or minimal code-level changes.

## Goals

- [ ] Development of search API with the new approach

## Expected Outcome

Search API as per the new approach that works seamlessly with all the existing domains and should be able to accommodate new domains.

## Acceptance Criteria

- [ ] Search API working with all current domains.

## Implementation Details

NA

## Mockups / Wireframes

NA

---

### Product Name

Beckn
### Project Name

strapi-plugin

### Organization Name:

FIDE

### Domain

NA

### Tech Skills Needed:

Strapi
Node

### Complexity

Medium

### Category
Feature

### Sub Category

API

**Comment by vishi24** [comment]
https://github.com/beckn/strapi-plugins/pull/16

**Comment by em-abee** [comment]
PR - https://github.com/beckn/strapi-plugins/pull/16
