### ISSUE TITLE
Tag based search

### ISSUE THREAD

**Issue by vishi24** [beckn/strapi-plugins#77]
## Description

The current Strapi plugin does not support tag based search.Implement the tag-based search , it should work as below
Tag based search (Tag match will be an exact match)

Example -
item.tags[0].list[0].descriptor.code = “vehicle-type“
item.tags[0].list[0].value = “4-wheeler“
item.tags[0].list[1].descriptor.code = “connector-type“
item.tags[0].list[1].value = “CCS“

## Goals

- [ ] BAP should be able to do a tag based search on Strapi BPP.

## Expected Outcome

Strapi should support tag based search.

## Acceptance Criteria

- [ ] BAP is able to make a tag based search.

**Comment by zoyaashik** [comment]
As per @em-abee request, This is skipped for today and working on to provide support and clear BE blockers for FE team as part of migration.

https://emindsworkspace.slack.com/archives/C051SDQRP38/p1712146000595389

**Comment by shreyvishal** [comment]
Current Status: done with the development, waiting for first [PR](https://github.com/beckn/strapi-plugins/pull/80) to be merged, then will raise the PR for this.
cc: @mayurvir @faizmagic

**Comment by shreyvishal** [comment]
Current Status: Done with the development raised [PR](https://github.com/beckn/strapi-plugins/pull/80), under review.
cc: @mayurvir @faizmagic

**Comment by shreyvishal** [comment]
Current Status: Done, and verified with Postman collection on Prod env
cc: @vishi24 @mayurvir @faizmagic

**Comment by shreyvishal** [comment]
Added: Original estimate was 4 hours and added extra 3 hours to the estimate. As @vishi24 pointed out an issue at code level and on debugging found out that the issue was not at code level but with the payload he was sending. Attaching payloads that he sent vs the correct payload expected.

Payload sent by @vishi24 
`{
    "context": {
        "domain": "{{tourism}}",
        "location": {
            "city": {
                "name": "Bangalore",
                "code": "std:080"
            },
            "country": {
                "name": "India",
                "code": "IND"
            }
        },
        "action": "search",
        "version": "1.1.0",
        "timestamp": "2023-10-09T04:46:28.012Z",
        "bap_uri": "{{bap_uri}}",
        "bap_id": "{{bap_id}}",
        "bpp_id": "{{bpp_id_ticket}}",
        "bpp_uri": "{{bpp_uri_ticket}}"
    },
    "message": {
        "intent": {
            "item": {
                "tags": [
                    {
                        "list": [
                            {
                                "descriptor": {
                                    "code": "National Park"
                                },
                                "value": "National Park"
                            }
                        ]
                    }
                ]
            }
        }
    }
}`


Correct Payload
`{
    "context": {
        "domain": "tourism",
        "location": {
            "city": {
                "name": "Bangalore",
                "code": "std:080"
            },
            "country": {
                "name": "India",
                "code": "IND"
            }
        },
        "action": "search",
        "version": "1.1.0",
        "timestamp": "2023-10-09T04:46:28.012Z",
        "bap_uri": "https://mit-ps-bap.becknprotocol.io",
        "bap_id": "mit-ps-bap.becknprotocol.io",
        "bpp_id": "mit-ps-tourism.becknprotocol.io",
        "bpp_uri": "https://mit-ps-tourism.becknprotocol.io"
    },
    "message": {
        "intent": {
            "item": {
                "tags": [
                    {
                        "list": [
                            {
                                "descriptor": {
                                    "code": "national_park"
                                },
                                "value": "National Park"
                            }
                        ]
                    }
                ]
            }
        }
    }
}`

cc: @faizmagic @mayurvir
