### ISSUE TITLE
Keyword based search

### ISSUE THREAD

**Issue by vishi24** [beckn/strapi-plugins#78]
## Description

The current Strapi plugin does not support keyword based search. Implement the keyword-based search , it should work as below

keywords - (contains based search on multiple columns)

Example-
intent.[Item.descriptor.](http://item.descriptor.name/)code = “ticket“
intent.[Item.descriptor.name](http://item.descriptor.name/)  = “yellow stone“
key word based search should  do a contains based search on multiple columns
name - current strapi implementation does only name search
short_desc  - need to implement
long_desc - need to implement

_Note-_
- item.descriptor.code should be exact match
- short_desc should be contains
- long_desc should be contains
- If all the four fields comes in the request then all the four fields should filtered.

## Goals

- [ ] BAP should be able to do a keyword based search on Strapi BPP.

## Expected Outcome

Strapi should support keyword based search.

## Acceptance Criteria

- [ ] BAP is able to make a keyword based search on multiple colunmns.

**Comment by shreyvishal** [comment]
Current Status: Done with the development, Raised PR for the same
PR Link: [Link](https://github.com/beckn/strapi-plugins/pull/80)
Description of work done: Added Conditional based logical **OR** Query creation, where is item.description.name is there then, strapi plugin will search for that name value in, 3 columns(name, long_desc, short_desc) irrespective of whether the data are provided to these specific fields.

cc: @mayurvir @faizmagic @em-abee
